version: '3'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./web:/usr/src/app
  db:
    platform: linux/amd64
    build: ./db
